name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [gcc]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true
#    - uses: actions/cache@v4
#      with:
#        path: /home/runner/.ccache
#        key: ccache:${{ matrix.os }}:${{ github.sha }}
#        restore-keys: 'ccache:${{ matrix.os }}:'
    - name: update
      run: |
        echo deb https://psha.org.ru/debian/ `echo ${{ matrix.os }} | tr -d -` contrib backports | sudo tee /etc/apt/sources.list.d/psha.org.ru.list
        sudo wget -O/etc/apt/trusted.gpg.d/psha.org.ru.gpg https://psha.org.ru/debian/pubkey.gpg
        sudo apt update
    - name: install deps
      run: sudo apt install ccache cmake meson pkg-config libfmt-dev libtll-dev libgtest-dev liblua5.3-dev python3-docutils python3-pytest python3-decorator python3-tll
    - name: configure
      run: meson build
    - name: build
      run: ninja -vC build -j2
    - name: test
      run: |
        meson test -C build --no-rebuild --print-errorlogs -v

# vim: sts=2 sw=2 et
